const places = {
  1: {
    openingTimeStatus: "Closed today",
    cmsRegion: "RegionSouthWest",
    imagePath: "/images/1431782871786-dsc0421.jpg",
    id: "1",
    title: "A la Ronde",
    subTitle: "Exmouth, Devon",
    description:
      "Quirky 18th-century, 16 sided house with fascinating interior decoration and collections",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431782871786-dsc0421.jpg",
    imageDescription: "A la Ronde in the sun",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/a-la-ronde",
    type: "Coast",
    location: {
      latitude: 50.641718,
      longitude: -3.408798,
    },
    activityTagsAsCsv: "Walking",
    displayable: true,
    petFriendly: true,
  },
  2: {
    openingTimeStatus: "Closed today",
    cmsRegion: "RegionWales",
    imagePath: "/images/1431737802588-aberc-ext-closeup-web.jpg",
    id: "2",
    title: "Aberconwy House",
    subTitle: "Conwy",
    description: "14th-century merchant's house",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431737802588-aberc-ext-closeup-web.jpg",
    imageDescription: "Aberconwy House, Conwy",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/aberconwy-house",
    type: "Countryside",
    location: {
      latitude: 53.282101,
      longitude: -3.82732,
    },
    displayable: true,
    petFriendly: false,
  },
  3: {
    openingTimeStatus: "Closed today",
    cmsRegion: "RegionWales",
    imagePath: "/images/1431767659249-aberdulais-in-winter.jpg",
    id: "3",
    title: "Aberdulais",
    subTitle: "Neath, Neath Port Talbot",
    description: "An Industrial Revolution, powered by water since 1584!",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431767659249-aberdulais-in-winter.jpg",
    imageDescription: "A winter walk at Aberdulais",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/aberdulais",
    type: "Gardens and Parks",
    location: {
      latitude: 51.680698,
      longitude: -3.77791,
    },
    activityTagsAsCsv: "Dog walking, Walking",
    displayable: true,
    petFriendly: true,
  },
  5: {
    openingTimeStatus: "Closed today",
    cmsRegion: "RegionNorthWest",
    imagePath: "/images/1431924387102-beechtree.jpg",
    id: "5",
    title: "Acorn Bank",
    subTitle: "near Penrith, Cumbria",
    description: "Delightful garden renowned for its herbs and fruit orchards",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431924387102-beechtree.jpg",
    imageDescription:
      "The 'Twisted Sister' beech tree at the entrance to the garden, at Acorn Bank",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/acorn-bank",
    type: "Coast",
    location: {
      latitude: 54.646301,
      longitude: -2.59228,
    },
    activityTagsAsCsv: "Dog walking, Geocaching, Walking",
    displayable: true,
    petFriendly: false,
  },
  6: {
    openingTimeStatus: "Closed today",
    cmsRegion: "RegionLondonSouthEast",
    imagePath: "/images/1431753700259-summer-veg-garden-resized-v2.jpg",
    id: "6",
    title: "Alfriston Clergy House",
    subTitle: "Polegate, East Sussex",
    description:
      "The first building saved forever for the nation by the National Trust ",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431753700259-summer-veg-garden-resized-v2.jpg",
    imageDescription: "Alfriston clergy house vegetable garden in summer",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/alfriston-clergy-house",
    type: "Countryside",
    location: {
      latitude: 50.803299,
      longitude: 0.16206,
    },
    activityTagsAsCsv: "Dog walking, Walking",
    displayable: true,
    petFriendly: true,
  },
  7: {
    openingTimeStatus: "Open today",
    cmsRegion: "RegionYorkshireNorthEast",
    imagePath: "/images/1431847604430-nationaltrustimagesdavidsellman.jpg",
    id: "7",
    title: "Allen Banks and Staward Gorge",
    subTitle: "Hexham, Northumberland",
    description:
      "Gorge of the River Allen with ornamental and ancient woodland",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431847604430-nationaltrustimagesdavidsellman.jpg",
    imageDescription: "Autumn at Allen banks ",
    alternativeImages: [],
    websiteUrl:
      "https://www.nationaltrust.org.uk/allen-banks-and-staward-gorge",
    type: "Gardens and Parks",
    location: {
      latitude: 54.964001,
      longitude: -2.31392,
    },
    activityTagsAsCsv: "Dog walking, Walking",
    displayable: true,
    petFriendly: false,
  },
  8: {
    openingTimeStatus: "Partially open today",
    cmsRegion: "RegionEastofEngland",
    imagePath: "/images/1431735497253-autumn-house.jpg",
    id: "9",
    title: "Anglesey Abbey, Gardens and Lode Mill",
    subTitle: "Cambridge, Cambridgeshire",
    description: "Jacobean-style house with gardens and a working watermill",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431735497253-autumn-house.jpg",
    imageDescription: "Autumn House ",
    alternativeImages: [],
    websiteUrl:
      "https://www.nationaltrust.org.uk/anglesey-abbey-gardens-and-lode-mill",
    type: "Coast",
    location: {
      latitude: 52.235915,
      longitude: 0.2448,
    },
    activityTagsAsCsv: "Cycling, Dog walking, Geocaching, Walking",
    displayable: true,
    petFriendly: true,
  },
  9: {
    cmsRegion: "RegionSouthWest",
    imagePath: "/images/1431731272389-1096672c.jpg",
    id: "900013",
    title: "Badbury Rings",
    subTitle: "",
    description: "Iron Age hillfort home to protected wildlife",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431731272389-1096672c.jpg",
    imageDescription: "Visitors at the Badbury Rings at Kingston Lacy, Dorset",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/badbury-rings",
    type: "Countryside",
    location: {
      latitude: 50.8272,
      longitude: -2.0583,
    },
    activityTagsAsCsv: "Dog walking",
    displayable: true,
    petFriendly: false,
  },
  10: {
    openingTimeStatus: "Open today",
    cmsRegion: "RegionEastofEngland",
    imagePath: "/images/1431874213215-12064441.jpg",
    id: "900012",
    title: "Morston Quay",
    subTitle: "Morston, Norfolk",
    description: "Explore the Norfolk Coast from Morston Quay",
    imageUrl:
      "https://nt.global.ssl.fastly.net/images/1431874213215-12064441.jpg",
    imageDescription:
      "Sunset over Morston Quay at Blakeney National Nature Reserve, Norfolk",
    alternativeImages: [],
    websiteUrl: "https://www.nationaltrust.org.uk/morston-quay",
    type: "Gardens and Parks",
    location: {
      latitude: 52.956741,
      longitude: 0.98656,
    },
    activityTagsAsCsv: "Dog walking",
    displayable: true,
    petFriendly: true,
  },
};

export default places;
